name: cicdworkshopdovbearworkflow
on:
  push:
    branches:
      - 'release/v[0-99].[0-999]'


jobs:
  namedoesnotmatter:
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/heads/release/v') && !contains(github.event.head_commit.message, '#NORUN')
    
    steps:
      # Check out Section
      - name: Checkout my code
        uses: actions/checkout@v3

      # Set up node
      - name: set node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
            
      # Deploy to Railway
      - name: send to railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "CICDWSdovbear"

      # Slack notification
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: 
          payload: | 
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "GdipSA 56 CI/CD Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* YAO BIN"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* ${{ secrets.MY_EMAIL_ADRESS }} "
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Matriculation:* A0127602N"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* ${{ secrets.MY_REPO_LINK }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ secrets.RAILWAY_URL }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "Go",
                    "url": "${{ secrets.RAILWAY_URL }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
